### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by dinrise** [tingirifistik/Steam-HourBooster#1]
https://i.imgur.com/ZDDW8BZ.png

empty when runing

**Comment by tingirifistik** [comment]
if you run on your own computer you should edit this part like this
![ss](https://user-images.githubusercontent.com/51286195/180652726-8b3e779a-684e-4c53-bcc5-79a0faa3b582.PNG)

**Comment by dinrise** [comment]
> if you run on your own computer you should edit this part like this ![ss](https://user-images.githubusercontent.com/51286195/180652726-8b3e779a-684e-4c53-bcc5-79a0faa3b582.PNG)

yes, i know. But dont work

**Comment by tingirifistik** [comment]
Nothing appears on the console except errors.(sorry i forgot to write this.)

Did you type the ' /start ' command in Telegram?

**Comment by dinrise** [comment]
yes. and nothing(

**Comment by tingirifistik** [comment]
I fixed it
