### ISSUE TITLE
not an issue but...

### ISSUE THREAD

**Issue by qsels** [tingirifistik/Steam-HourBooster#3]
the config system inside of the telegram bot was so broken i literally had to create my own config file and put in the stuff manually into the file because of how broken it was

**Comment by Lcs290** [comment]
> the config system inside of the telegram bot was so broken i literally had to create my own config file and put in the stuff manually into the file because of how broken it was

How did you fix this?

**Comment by tingirifistik** [comment]
@qsels I fixed it
