### ISSUE TITLE
Error codes are outdated

### ISSUE THREAD

**Issue by JuanMaDev98** [tingirifistik/Steam-HourBooster#6]
The error codes are outdated, instead of error codes now returns the error itself
for example:

str(account_login) == "1"

Should be now:

str(account_login) == "EResult.OK"

**Comment by tingirifistik** [comment]
hi,
In python, enum types are designed to hold both numerical values and names.So when checking error conditions, you can compare enum values using either their numerical values or their names. For instance the expression EResult.OK matches both the numerical value 1 and the name "EResult.OK".
